name: Hourly Commit

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Commit Content
        run: |
          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          echo "🤖 Automated commit: $timestamp" >> commit_log.txt

      - name: Commit Changes
        run: |
          git config user.name nhim411
          git config user.email lehoainam1998@gmail.com
          git add commit_log.txt
          git commit -m "Auto commit: $(date '+%Y-%m-%d %H:%M:%S')" || exit 0
          git push
