name: Daily Reminder
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit and push changes
        run: |
          echo "Automatic daily commit - $(date)" >> README.md
          git config --global user.email "lehoainam1998@gmail.com"
          git config --global user.name "namlh"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatic daily commit $(date)" && git push)